version: '3.8'

networks:
  notification-network:
    driver: bridge

volumes:
  sqlite-data:

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - notification-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_MAX_REQUEST_SIZE=2097152000  # Increase to 2 GB
      - KAFKA_MESSAGE_MAX_BYTES=2097152000  # Increase to 2 GB
    depends_on:
      - zookeeper
    networks:
      - notification-network

  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - notification-network

  konga:
    image: pantsel/konga:latest
    environment:
      - NODE_ENV=production
    ports:
      - "1337:1337"
    depends_on:
      - kong
    networks:
      - notification-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    volumes:
      - sqlite-data:/app/data
    networks:
      - notification-network

  producer-frontend:
    build:
      context: ./frontend/producer
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - notification-network

  consumer-frontend:
    build:
      context: ./frontend/consumer
    ports:
      - "8502:8502"
    depends_on:
      - backend
    networks:
      - notification-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka
    networks:
      - notification-network
