version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: ./backend/.env
    environment:
      GOOGLE_API_KEY: "AIzaSyC0hsZyfhbr_1PR0VzxXOfZcpQIgI1IqYg"
      SEARCH_ENGINE_ID: "203ea2c7021574507"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my-api-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - my-api-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dishes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net

volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:
    driver: bridge

